version: "3.8"

services:
  spacemonger-api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file:
      - ./.env
    depends_on:
      - postgres

  spacemongerd:
    build:
      context: .
      dockerfile: docker/daemon/Dockerfile
    env_file:
      - ./.env
    depends_on:
      - postgres
    command:
      - watch
      - scan-system

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: spacemonger
      POSTGRES_DB: spacemonger
      POSTGRES_PASSWORD: 2djlsUYwcF0YzSgvTZPc9BCWff
    ports:
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d

volumes:
  pg_data:
