version: 2.1

jobs:
  build:
    working_directory: /app
    docker:
      image: 
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t bloveless/spacemongerd:$TAG -f ./docker/daemon/Dockerfile .

workflows:
  build:
    jobs:
      - build
