apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacemongerd
  namespace: spacemonger
  labels:
    app: spacemonger
    component: spacemongerd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacemonger
      component: spacemongerd
  template:
    metadata:
      labels:
        app: spacemonger
        component: spacemongerd
    spec:
      containers:
      - name: spacemongerd-trader
        image: bloveless/spacemongerd
        command: ["/app/spacemongerd"]
        envFrom:
        - secretRef:
            name: spacemonger
        env:
        - name: USERNAME_BASE
          value: bloveless
        - name: POSTGRES_HOST
          value: 192.168.4.252
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_USERNAME
          value: spacemonger
        - name: POSTGRES_DATABASE
          value: spacemonger
        - name: ENABLE_TRADER
          value: "true"
        - name: ENABLE_SCOUTS
          value: "false"
        - name: ENABLE_RESET
          value: "true"
        - name: RUST_LOG
          value: spacemongerd=debug,spacetraders=info
      - name: spacemongerd-scouts
        image: bloveless/spacemongerd
        command: ["/app/spacemongerd"]
        envFrom:
          - secretRef:
              name: spacemonger
        env:
          - name: USERNAME_BASE
            value: bloveless
          - name: POSTGRES_HOST
            value: 192.168.4.252
          - name: POSTGRES_PORT
            value: '5432'
          - name: POSTGRES_USERNAME
            value: spacemonger
          - name: POSTGRES_DATABASE
            value: spacemonger
          - name: ENABLE_TRADER
            value: "false"
          - name: ENABLE_SCOUTS
            value: "true"
          - name: ENABLE_RESET
            value: "false"
          - name: RUST_LOG
            value: spacemongerd=debug,spacetraders=trace
          - name: HTTP_PROXY
            value: 127.0.0.1:9080
      - name: tor
        image: bloveless/tor
        ports:
          - containerPort: 9080
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacemonger-api
  namespace: spacemonger
  labels:
    app: spacemonger
    component: spacemonger-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacemonger
      component: spacemonger-api
  template:
    metadata:
      labels:
        app: spacemonger
        component: spacemonger-api
    spec:
      containers:
        - name: spacemonger-api
          image: bloveless/spacemonger-api
          command: ["/app/spacemonger-api"]
          envFrom:
            - secretRef:
                name: spacemonger
          env:
            - name: USERNAME_BASE
              value: bloveless
            - name: POSTGRES_HOST
              value: 192.168.4.252
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_USERNAME
              value: spacemonger
            - name: POSTGRES_DATABASE
              value: spacemonger
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacemonger-ui
  namespace: spacemonger
  labels:
    app: spacemonger
    component: spacemonger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacemonger
      component: spacemonger-ui
  template:
    metadata:
      labels:
        app: spacemonger
        component: spacemonger-ui
    spec:
      containers:
        - name: spacemonger-ui
          image: bloveless/spacemonger-ui
      restartPolicy: Always
