apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacemongerd
  namespace: spacemonger
  labels:
    app: spacemonger
    component: spacemongerd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacemonger
      component: spacemongerd
  template:
    metadata:
      labels:
        app: spacemonger
        component: spacemongerd
    spec:
      containers:
      - name: spacemongerd
        image: bloveless/spacemongerd
        command: ["/app/spacemongerd"]
        envFrom:
        - secretRef:
            name: spacemonger
        env:
        - name: USERNAME
          value: bloveless2
        - name: ENABLE_TRADER_LOGS
          value: "true"
        - name: ENABLE_SCOUT_LOGS
          value: "true"
        - name: ENABLE_RESET
          value: "true"
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacemonger-api
  namespace: spacemonger
  labels:
    app: spacemonger
    component: spacemonger-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacemonger
      component: spacemonger-api
  template:
    metadata:
      labels:
        app: spacemonger
        component: spacemonger-api
    spec:
      containers:
        - name: spacemonger-api
          image: bloveless/spacemonger-api
          command: ["/app/spacemonger-api"]
          envFrom:
            - secretRef:
                name: spacemonger
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacemonger-ui
  namespace: spacemonger
  labels:
    app: spacemonger
    component: spacemonger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacemonger
      component: spacemonger-ui
  template:
    metadata:
      labels:
        app: spacemonger
        component: spacemonger-ui
    spec:
      containers:
        - name: spacemonger-ui
          image: bloveless/spacemonger-ui
      restartPolicy: Always
