apiVersion: v1
kind: Pod
metadata:
  name: spacetraders
  namespace: spacetraders
  labels:
    app: spacetraders
spec:
  containers:
  - name: spacetraders
    image: bloveless/spacetraders:0.1.0-alpha.7
    command: ["/app/spacetraders-rs"]
    envFrom:
    - secretRef:
        name: spacetraders
    env:
    - name: USERNAME_BASE
      value: bloveless
    - name: POSTGRES_HOST
      value: 192.168.4.252
    - name: POSTGRES_PORT
      value: '5432'
    - name: POSTGRES_USERNAME
      value: spacetraders
    - name: POSTGRES_DATABASE
      value: spacetraders
  restartPolicy: Always
