apiVersion: v1
kind: Pod
metadata:
  name: spacetradersd
  namespace: spacetraders
  labels:
    component: spacetradersd
spec:
  containers:
  - name: spacetradersd
    image: bloveless/spacetradersd:0.1.0-alpha.1
    command: ["/app/spacetradersd"]
    envFrom:
    - secretRef:
        name: spacetraders
    env:
    - name: USERNAME_BASE
      value: bloveless
    - name: POSTGRES_HOST
      value: 192.168.4.252
    - name: POSTGRES_PORT
      value: '5432'
    - name: POSTGRES_USERNAME
      value: spacetraders
    - name: POSTGRES_DATABASE
      value: spacetraders
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: spacetraders-api
  namespace: spacetraders
  labels:
    component: spacetraders-api
spec:
  containers:
    - name: spacetraders-api
      image: bloveless/spacetraders-api:0.1.0-alpha.2
      command: ["/app/spacetraders-api"]
      envFrom:
        - secretRef:
            name: spacetraders
      env:
        - name: USERNAME_BASE
          value: bloveless
        - name: POSTGRES_HOST
          value: 192.168.4.252
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_USERNAME
          value: spacetraders
        - name: POSTGRES_DATABASE
          value: spacetraders
  restartPolicy: Always
