apiVersion: v1
kind: Pod
metadata:
  name: spacemongerd
  namespace: spacemonger
  labels:
    app: spacemonger
    component: spacemonger
spec:
  containers:
  - name: spacemongerd
    image: bloveless/spacemongerd:0.1.0-alpha.6
    command: ["/app/spacemongerd"]
    envFrom:
    - secretRef:
        name: spacemonger
    env:
    - name: USERNAME_BASE
      value: bloveless
    - name: POSTGRES_HOST
      value: 192.168.4.252
    - name: POSTGRES_PORT
      value: '5432'
    - name: POSTGRES_USERNAME
      value: spacemonger
    - name: POSTGRES_DATABASE
      value: spacemonger
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: spacemonger-api
  namespace: spacemonger
  labels:
    app: spacemonger
    component: spacemonger-api
spec:
  containers:
    - name: spacemonger-api
      image: bloveless/spacemonger-api:0.1.0-alpha.4
      command: ["/app/spacemonger-api"]
      envFrom:
        - secretRef:
            name: spacemonger
      env:
        - name: USERNAME_BASE
          value: bloveless
        - name: POSTGRES_HOST
          value: 192.168.4.252
        - name: POSTGRES_PORT
          value: '5432'
        - name: POSTGRES_USERNAME
          value: spacemonger
        - name: POSTGRES_DATABASE
          value: spacemonger
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: spacemonger-ui
  namespace: spacemonger
  labels:
    app: spacemonger
    component: spacemonger-ui
spec:
  containers:
    - name: spacemonger-ui
      image: bloveless/spacemonger-ui:0.1.0-alpha.2
  restartPolicy: Always
