apiVersion: v1
kind: Service
metadata:
  name: spacetraders-api-service
  namespace: spacetraders
spec:
  type: ClusterIP
  selector:
    app: spacetraders
    component: spacetraders-api
  ports:
    - name: spacetraders-api
      port: 8080
      targetPort: 8080
